import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Sora Video Generation",
  description: "Generated by sora application",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          " min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        {children}
        <Footer />
        <Script
          async
          src="https://umami.runningpig.top/script.js"
          data-website-id="83e47a06-f115-491b-aa69-a74717726abb"
        ></Script>
      </body>
    </html>
  );
}
